### ISSUE TITLE
[BUG] Reorderpolydata will occasionally crash 

### ISSUE THREAD

**Issue by wuzhuobin** [wuzhuobin/blood_vessel#30]
when it is used in generating contourwidget, which need the point id of polydata in a well defined loop order. but some time the reorder algorithm cannot find the first point, while it must find which lead it crash.

**Comment by wuzhuobin** [comment]
fixed by the upper commit.

**Comment by wuzhuobin** [comment]
wtf... crash again 
it looks like GetId(0) is not always be found in this situation.


                      LumenSegmentationFilter2.cxx 119
crash here->	if (neighborPtID->GetId(0) != l_looper) {
				neighborPtId2 = neighborPtID->GetId(0);
			}
			else {
				neighborPtId2 = neighborPtID->GetId(1);
			}

			memcpy(vectorLooper, lumenWallPolyData->GetPoint(l_looper), sizeof(double) * 3);
			memcpy(vector1, lumenWallPolyData->GetPoint(neighborPtId1), sizeof(double) * 3);
			memcpy(vector2, lumenWallPolyData->GetPoint(neighborPtId2), sizeof(double) * 3);

**Comment by alabamagan** [comment]
The algorithm uses point ID 0 as the starting point of the search (which is quite reasonable IMO), so if the polydata cleaner happens to clean away the zero point, something might happen.
btw, lol use triple  '  -> \'\'\'code here...\'\'\'  to quote codes

**Comment by wuzhuobin** [comment]
@teracamo 
2 situations it crashed
![image](https://cloud.githubusercontent.com/assets/17057846/20621355/17d6725c-b339-11e6-8fbe-a4acd831570e.png)
![image](https://cloud.githubusercontent.com/assets/17057846/20621364/26adddc4-b339-11e6-982c-e44b0ab27a2e.png)

**Comment by alabamagan** [comment]
Hmm are those loops?

Get Outlook for iOS




On Fri, Nov 25, 2016 at 6:01 PM +0800, "wuzhuobin" <notifications@github.com> wrote:












@teracamo

2 situations it crashed

**Comment by alabamagan** [comment]
If it's not loop or there are not zeroth ID, both situations lead to crashes. Try to do error check. 
Get Outlook for iOS

		_____________________________

**Comment by wuzhuobin** [comment]
![image](https://cloud.githubusercontent.com/assets/17057846/20780609/3d86909a-b7b7-11e6-9f02-2124a9681e9b.png)
![image](https://cloud.githubusercontent.com/assets/17057846/20780613/45394238-b7b7-11e6-91e4-23f5a2155117.png)

2 new situations

**Comment by wuzhuobin** [comment]
[reorder.zip](https://github.com/wuzhuobin/blood_vessel/files/623627/reorder.zip)
reorder cases

**Comment by alabamagan** [comment]
Branching has problem for sure. 
Maybe use tree span

Get Outlook for iOS




On Thu, Dec 1, 2016 at 11:14 AM +0800, "wuzhuobin" <notifications@github.com> wrote:

















2 new situations
