### ISSUE TITLE
[BUG] InteracorStyleSeedsPlacer Update with little bugs

### ISSUE THREAD

**Issue by wuzhuobin** [wuzhuobin/blood_vessel#31]
Now the seeds can be modified with draging by mouse. but sometimes the coordinates of seeds will go to [-857xxxx, -857xxxx, -857xxxx], which is uninitialized? 
this situation will happen with dragging by mouse

**Comment by alabamagan** [comment]
Maybe the ray cast doesn't hit anything? Write a clamp to extent to solve this?
Get Outlook for iOS

On Thu, Nov 10, 2016 at 10:56 PM +0800, "wuzhuobin" notifications@github.com wrote:

Now the seeds can be modified with draging by mouse. but sometimes the coordinates of seeds will go to [-857xxxx, -857xxxx, -857xxxx], which is uninitialized?

this situation will happen with dragging by mouse
