### ISSUE TITLE
[Bug] Change mode from multi-planer view to all-axial view

### ISSUE THREAD

**Issue by wuzhuobin** [wuzhuobin/blood_vessel#32]
the interactorstyle has never considered this situation. if the interactorstyle is related to deal with widgets or adding new actors, it will not be turn off by now. it should be fixed some day.

**Comment by alabamagan** [comment]
What do you mean by cannot turn off?

Get Outlook for iOS

On Sat, Nov 19, 2016 at 9:06 PM +0800, "wuzhuobin" notifications@github.com wrote:

the interactorstyle has never considered this situation. if the interactorstyle is related to deal with widgets or adding new actors, it will not be turn off by now. it should be fixed some day.
