### ISSUE TITLE
[BUG] Crash when deleting last point of a contour created with "Normal Contour"

### ISSUE THREAD

**Issue by alabamagan** [wuzhuobin/blood_vessel#49]

**Comment by wuzhuobin** [comment]
this problem is temporary fixed by 
CoutourWidgetSeries.cxx line 239
`
                // else conduct to contours
		self->InvokeEvent(vtkCommand::InteractionEvent, NULL);
		// fixing a bug that the vtkCommand#MouseMoveEvent can invoke accessing the first 
		// point of vtkOrientGlyphContourRepresentation#FocalPoint, it is a tricky bug and 
		// I don't want to know why, just a temporary fixation. 
		if (self->Contours->size() != 0 && 
			self->Contours->back()->GetContourRepresentation()->GetNumberOfNodes() > 1) {
			self->InvokeEvent(vtkCommand::MouseMoveEvent, NULL);
		}
`

**Comment by alabamagan** [comment]
Just make a commit, i am not working on the code currently

________________________________

**Comment by alabamagan** [comment]
We should remember to fix this later

**Comment by alabamagan** [comment]
I think the modification is a good fix
